"""feature: adds user e item table

Revision ID: 199f0e2079e5
Revises: 
Create Date: 2021-08-14 15:06:13.766234

"""

# revision identifiers, used by Alembic.
revision = '199f0e2079e5'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('hashed_password', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        schema='us'
    )
    op.create_index(op.f('ix_us_users_email'), 'users', ['email'], unique=True, schema='us')
    op.create_index(op.f('ix_us_users_id'), 'users', ['id'], unique=False, schema='us')
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('owner_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['owner_id'], ['us.users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        schema='us'
    )
    op.create_index(op.f('ix_us_items_description'), 'items', ['description'], unique=False, schema='us')
    op.create_index(op.f('ix_us_items_id'), 'items', ['id'], unique=False, schema='us')
    op.create_index(op.f('ix_us_items_title'), 'items', ['title'], unique=False, schema='us')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_us_items_title'), table_name='items', schema='us')
    op.drop_index(op.f('ix_us_items_id'), table_name='items', schema='us')
    op.drop_index(op.f('ix_us_items_description'), table_name='items', schema='us')
    op.drop_table('items', schema='us')
    op.drop_index(op.f('ix_us_users_id'), table_name='users', schema='us')
    op.drop_index(op.f('ix_us_users_email'), table_name='users', schema='us')
    op.drop_table('users', schema='us')
    # ### end Alembic commands ###
