"""database model of catalogo

Revision ID: fa639c878ec4
Revises: 
Create Date: 2021-08-14 12:50:05.317027

"""

# revision identifiers, used by Alembic.
revision = 'fa639c878ec4'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attribute',
        sa.Column('nbr', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('available', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('nbr'),
        schema='cat'
    )
    op.create_table('department',
        sa.Column('nbr', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('nbr'),
        schema='cat'
    )
    op.create_table('attribute_detail',
        sa.Column('nbr', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('available', sa.Boolean(), nullable=False),
        sa.Column('attribute_nbr', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['attribute_nbr'], ['cat.attribute.nbr'], ),
        sa.PrimaryKeyConstraint('nbr'),
        schema='cat'
    )
    op.create_index(op.f('ix_cat_attribute_detail_attribute_nbr'), 'attribute_detail', ['attribute_nbr'], unique=False, schema='cat')
    op.create_table('category',
        sa.Column('nbr', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('isOnline', sa.Boolean(), nullable=False),
        sa.Column('department_nbr', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['department_nbr'], ['cat.department.nbr'], ),
        sa.PrimaryKeyConstraint('nbr'),
        schema='cat'
    )
    op.create_index(op.f('ix_cat_category_department_nbr'), 'category', ['department_nbr'], unique=False, schema='cat')
    op.create_table('category_attribute',
        sa.Column('category_nbr', sa.Integer(), nullable=False),
        sa.Column('attribute_nbr', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['attribute_nbr'], ['cat.attribute.nbr'], ),
        sa.ForeignKeyConstraint(['category_nbr'], ['cat.category.nbr'], ),
        sa.PrimaryKeyConstraint('category_nbr', 'attribute_nbr'),
        schema='cat'
    )
    op.create_index(op.f('ix_cat_category_attribute_attribute_nbr'), 'category_attribute', ['attribute_nbr'], unique=False, schema='cat')
    op.create_index(op.f('ix_cat_category_attribute_category_nbr'), 'category_attribute', ['category_nbr'], unique=False, schema='cat')
    op.create_table('product',
        sa.Column('nbr', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('isOnline', sa.Boolean(), nullable=False),
        sa.Column('available', sa.Boolean(), nullable=False),
        sa.Column('price', sa.Integer(), nullable=False),
        sa.Column('category_nbr', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['category_nbr'], ['cat.category.nbr'], ),
        sa.PrimaryKeyConstraint('nbr'),
        schema='cat'
    )
    op.create_index(op.f('ix_cat_product_category_nbr'), 'product', ['category_nbr'], unique=False, schema='cat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cat_product_category_nbr'), table_name='product', schema='cat')
    op.drop_table('product', schema='cat')
    op.drop_index(op.f('ix_cat_category_attribute_category_nbr'), table_name='category_attribute', schema='cat')
    op.drop_index(op.f('ix_cat_category_attribute_attribute_nbr'), table_name='category_attribute', schema='cat')
    op.drop_table('category_attribute', schema='cat')
    op.drop_index(op.f('ix_cat_category_department_nbr'), table_name='category', schema='cat')
    op.drop_table('category', schema='cat')
    op.drop_index(op.f('ix_cat_attribute_detail_attribute_nbr'), table_name='attribute_detail', schema='cat')
    op.drop_table('attribute_detail', schema='cat')
    op.drop_table('department', schema='cat')
    op.drop_table('attribute', schema='cat')
    # ### end Alembic commands ###
